encoding: utf-8

exclude:
  - .editorconfig
  - .npmrc
  - .prettierignore
  - .prettierrc.json
  - LICENSE
  - README.md
  - doc/
  - html/
  - js/lib/README.md
  - package-lock.json
  - package.json
  - script/
  - server.js
